export const TASK_CATEGORIES = [
  {
    name: 'Böden',
    tasks: [
      'Hartböden feucht wischen & Textilbeläge saugen',
      'Böden kehren',
      'Böden desinfizieren',
      'Fußleisten feucht reinigen',
      'Fußleisten entstauben',
      'Grundreinigung Böden',
    ],
  },
  {
    name: 'Sanitär',
    tasks: [
      'WC-Oberflächen, WC-Sitze & Spülungen säubern',
      'WC Fliesenwände reinigen',
      'Waschbecken, Armaturen & Wandspiegel reinigen',
      'Duschköpfe reinigen',
      'Duschkabinen reinigen und entkalken',
      'Urinale reinigen und desinfizieren',
      'Grundreinigung Sanitärbereiche',
    ],
  },
  {
    name: 'Glas & Fenster',
    tasks: [
      'Fensterscheiben reinigen innen/außen',
      'Fensterbänke feucht wischen',
      'Fensterrahmen abwischen',
      'Glasflächen innen und außen reinigen',
      'Glasscheiben von Fingerabdrücken befreien',
      'Türverglasung reinigen',
      'Lamellenreinigung (Jalousien/Sonnenschutz)',
    ],
  },
  {
    name: 'Oberflächen',
    tasks: [
      'Schreibtische feucht abwischen',
      'Arbeitstische reinigen',
      'Besprechungstische feucht abwischen',
      'Türklinken & Lichtschalter desinfizieren',
      'Handläufe abwischen',
      'Heizkörper abwischen',
      'Steckdosen & Schalter reinigen',
      'Tresen & Ablageflächen reinigen',
      'Sitzflächen abwischen',
    ],
  },
  {
    name: 'Abfall',
    tasks: ['Abfalleimer entleeren inkl. Austausch der Beutel', 'Sonderabfall gesondert entsorgen'],
  },
  {
    name: 'Spinnweben & Staub',
    tasks: [
      'Staub & Spinnweben entfernen an Decken und in Ecken',
      'Entstauben der Physiogeräte',
      'Bildschirme & Tastaturen entstauben',
    ],
  },
  {
    name: 'Küche',
    tasks: [
      'Arbeitsflächen reinigen und desinfizieren',
      'Spüle reinigen und desinfizieren',
      'Kühlschrank außen abwischen',
      'Mikrowelle innen & außen reinigen',
      'Kaffeemaschine reinigen',
      'Geschirrspüler außen abwischen',
    ],
  },
  {
    name: 'Sonstiges',
    tasks: [
      'Seifen- & Handtuchspender auffüllen',
      'Desinfektionsmittelspender auffüllen',
      'Toilettenpapier & Hygieneartikel auffüllen',
      'Liegen & Behandlungsflächen desinfizieren',
      'Aufzugskabine reinigen',
      'Hauseingang & Fußmatte reinigen',
      'Briefkastenanlage abwischen',
      'Kellerflur kehren',
      'Waschküche reinigen',
      'Umkleiden reinigen',
      'Pausenraum reinigen',
      'Verkehrswege feucht wischen',
      'Grobschmutz & Fremdkörper entfernen',
      'Kehren & maschinelle Bodenreinigung großflächig',
      'Gehwege von Schnee räumen',
      'Gehwege bei Glätte abstreuen',
      'Zufahrten & Parkplätze räumen',
      'Treppen & Eingangsbereiche räumen und streuen',
      'Streugut nach Tauwetter entfernen/kehren',
      'Kontrolle und Nachstreuen im Tagesverlauf',
    ],
  },
];
