// Built-in library of common cleaning task descriptions, used for
// autocomplete suggestions while editing a row's description field.
export const TASK_SUGGESTIONS = [
  'Fußleisten feucht reinigen',
  'Fußleisten entstauben',
  'Fußleisten wischen',
  'Hartböden feucht wischen & Textilbeläge saugen',
  'Böden kehren',
  'Böden desinfizieren',
  'Böden saugen und feucht wischen',
  'Grundreinigung Böden',
  'Fensterscheiben reinigen innen/außen',
  'Fensterbänke feucht wischen',
  'Fensterrahmen abwischen',
  'Glasflächen innen und außen reinigen',
  'Glasscheiben von Fingerabdrücken befreien',
  'Türverglasung reinigen',
  'WC-Oberflächen, WC-Sitze & Spülungen säubern',
  'WC Fliesenwände reinigen',
  'Urinale reinigen und desinfizieren',
  'Schreibtische feucht abwischen',
  'Arbeitstische reinigen',
  'Besprechungstische feucht abwischen',
  'Waschbecken, Armaturen & Wandspiegel reinigen',
  'Duschköpfe reinigen',
  'Duschkabinen reinigen und entkalken',
  'Grundreinigung Sanitärbereiche',
  'Abfalleimer entleeren inkl. Austausch der Beutel',
  'Sonderabfall gesondert entsorgen',
  'Staub & Spinnweben entfernen an Decken und in Ecken',
  'Entstauben der Physiogeräte',
  'Bildschirme & Tastaturen entstauben',
  'Türklinken & Lichtschalter desinfizieren',
  'Handläufe abwischen',
  'Treppenstufen kehren und feucht wischen',
  'Aufzugskabine reinigen',
  'Hauseingang & Fußmatte reinigen',
  'Briefkastenanlage abwischen',
  'Kellerflur kehren',
  'Waschküche reinigen',
  'Arbeitsflächen reinigen und desinfizieren',
  'Spüle reinigen und desinfizieren',
  'Kühlschrank außen abwischen',
  'Mikrowelle innen & außen reinigen',
  'Kaffeemaschine reinigen',
  'Geschirrspüler außen abwischen',
  'Seifen- & Handtuchspender auffüllen',
  'Desinfektionsmittelspender auffüllen',
  'Toilettenpapier & Hygieneartikel auffüllen',
  'Liegen & Behandlungsflächen desinfizieren',
  'Tresen & Ablageflächen reinigen',
  'Sitzflächen abwischen',
  'Lamellenreinigung (Jalousien/Sonnenschutz)',
  'Heizkörper abwischen',
  'Steckdosen & Schalter reinigen',
  'Bodenablauf reinigen',
  'Umkleiden reinigen',
  'Pausenraum reinigen',
  'Verkehrswege feucht wischen',
  'Grobschmutz & Fremdkörper entfernen',
  'Kehren & maschinelle Bodenreinigung großflächig',
  'Gehwege von Schnee räumen',
  'Gehwege bei Glätte abstreuen',
  'Zufahrten & Parkplätze räumen',
  'Treppen & Eingangsbereiche räumen und streuen',
  'Streugut nach Tauwetter entfernen/kehren',
  'Kontrolle und Nachstreuen im Tagesverlauf',
];

export function getSuggestions(query, limit = 8) {
  const q = query.trim().toLowerCase();
  if (!q) return [];
  return TASK_SUGGESTIONS.filter((s) => s.toLowerCase().includes(q)).slice(0, limit);
}
